name: pr-agent

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    name: Run PR Agent
    steps:
      - id: pr-agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          github_action.auto_describe: true
          github_action.auto_review: true
          github_action.auto_improve: true
          PR_REVIEWER.EXTRA_INSTRUCTIONS: >- 
            日本語で回答してください。 
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: >- 
            日本語で回答してください。
            タイトルは feat: 、chore: 、test: 、fix: 、ci: 、docs: などの
            commitlint パターンの接頭辞を含む必要があります。
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: '日本語で記述してください。'
          CONFIG.MODEL: gpt-4-1106-preview
